---
title: '2019-03-13'
author: "林茂廷"
date: "3/13/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
88 -> A
```


```{r}
62 + A  
```

```{r}
avactor{1 , 2 ,3}
```

```{r}
library(lubridate)
```
```{r}
dtObject<-ymd_hms("1970-01-01 00:02:53") 
```

```{r}
dtObjectVector<-ymd_hms(
  c("1970-01-01 00:02:53",
    "1980-02-11 11:25:22")
)
```

```{r}
class(dtObject)
```

```{r}
Sys.timezone()
```
```{r}
twDateTime <- ymd_hms("2019-03-27 14:04:00", tz="Asia/Taipei")
```

```{r}
LisbonDateTime <- with_tz(twDateTime,tzone="Europe/Lisbon")
LisbonDateTime
```
```{r}
twDateTime <- mdy ("March 3, 2019", tz="Asia/Taipei")
twDateTime
```
```{r}
aL <- c(1L, 5L, -3L)
bL <- c(-2L, -4L, 8L)
aL+bL
```

```{r}
aL+4
```
```{r}
aL**2
aL*2
aL/bL
```
```{r}
startingDate <- ymd("2000-02-17")
```

```{r}
startingDate + years(1)
```
```{r}
startingDate + dyears(1)
```
```{r}
x <- 5
y <- 7
x < y
```

```{r}
x == y
```

```{r}
x2 <- c(1,5,10)
y2 <- c(-1,5,20)
```
```{r}
x2 == y2
```
```{r}
x4 <- c(1,5,8)
y4 <- c(5,8)
x4 %in% y4
```
```{r}
x2 <- c(1,NA,10)
y2 <- c(NA,NA,20)

x3 <- c(NA,"小花")
y3 <- c(NA,"小華")

is.na(x2)
```
```{r}
is.na(y3)
```

```{r}
x3 <- c("小明","小花")
y3 <- c("小明","小華")
```

```{r}
x3 == y3
```
```{r}
x5 <- c("台北市","新北市","高雄市")
y5 <- c("台北市","新北市")

x5 %in% y5
```



```{r}
library (readr)
exData2 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData2.csv")
currency <- exData2$ 幣別
```
```{r}
install.packages("readr")
```

```{r}
head(currency)
```
```{r}
class(currency)
```
```{r}
currency < - as.factor(currency)
class(currency)
```

```{r}
levels(currency)
```

```{r}
length(levels(currency))
```

```{r}
currency2 <- c("日元","美元","日元")
currency2
```


```{r}
sum(currency2 == "日元")
```

```{r}
head(currency)
sum(currency == "日圓JPY/USD")
```
```{r}
x5 <- c("台北市","新北市","高雄市")
greatTaipei <- c("台北市","新北市")

x5 %in% greatTaipei
!(x5 %in% greatTaipei)
```

```{r}
y5 <- c("女","男","女")

y5
y5=="女"
!(y5=="女")
```
```{r}
(x5 %in% greatTaipei) & (y5=="女")
```
```{r}
(x5 %in% greatTaipei) | (y5=="女")
```

```{r}
xor(x5 %in% greatTaipei, y5=="女") 
```
```{r}
install.packages("stringr")
```

```{r}
library(stringr)
```

```{r}
library(readr)
transcriptDataFinal <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/transcriptDataFinal.csv")
courseType <- transcriptDataFinal$`必選修類別（必∕選∕通）`
major <- transcriptDataFinal$學系
studentID <- transcriptDataFinal$學號
grade <- transcriptDataFinal$學期成績
```

```{r}
course <- c("個體經濟學","投資學","總體經濟學")
```
```{r}
month <- c("3","4","2")
day <- c("11","5","7")
```

```{r}
chineseDate <- c("3月11日","4月5日","2月7日")
```


```{r}
studentID<-c(
  '410177115','410176080','410174233','410177011','410182045','410176014')
系別<-str_sub(studentID,5,6)
系別
入學年<-str_sub(studentID,2,4)
入學年
```

```{r}
char1 <- c("月","月","月")
char2 <- c("日","日","日")
month
char1
day 
char2
str_c(month,char1,day,char2)
```
```{r}
str_c(char2,char1,day,month)
```

```{r}
month
day
str_c(month,day, sep="-")
str_c(day,month, sep = "+")
```

```{r}
plasticContainer <- list(
  greenBox=c("paper","scissor"),     # location 1
  redBox=c(1,3,2.5),               # location 2
  blueBox=c(TRUE,FALSE,TRUE,TRUE)    # location 3
)
```

```{r}
plasticContainer[["greenBox"]] 
plasticContainer[[1]]
```

```{r}
x <- plasticContainer[["greenBox"]] 
x[[1]]
```
```{r}
成績單 <- c(
  個經=90,
  總經=77,
  統計=88
)
```
```{r}
成績單[[1]]
```
```{r}
plasticContainer[c("greenBox","redBox")] 
plasticContainer[c(1,2)]
```
```{r}
plasticContainer[c("greenBox","redBox")] 

```

```{r}
extract1 <- plasticContainer[c("greenBox")]
```
```{r}
extract2 <- plasticContainer[[c("greenBox")]]
```
```{r}
extract1[[1]][[1]]
extract2[[1]]
```
```{r}
length(plasticContainer)
plasticContainer[c(T,F,T)]
```
```{r}
成績單
成績單[c(FALSE,TRUE,TRUE)]
```

```{r}
plasticContainer$greenBox
plasticContainer[["greenBox"]]
```
```{r}
install.packages("httr, stringr")
```
```{r}
your_github_username <- "tpemartin"
your_practice_reponame <- "107-2-inclass-practice"
library(httr)
library(stringr)
str_replace_all(
  "https://api.github.com/repos/:owner/:repo/commits",
  c(
    ":owner"=your_github_username,
    ":repo"=your_practice_reponame
    )
  ) -> commitCheckStatement
commitCheck <- content(GET(commitCheckStatement))
```

```{r}
commitCheck[["message"]]
```
```{r}
library(readr)
filmVotingData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/podcastcompetition3.csv")
str_replace(filmVotingData$請選擇你最喜歡的影片二部,", by"," by") -> favoriteTwo
birthday <- filmVotingData$`出生西元年月日（驗證本人用）`
timeStamp <- filmVotingData$Timestamp
```
```{r}
logiCorrect <- str_length(birthday)==8
logiCorrect
```

```{r}
str_length(birthday) == 8
```
```{r}
m2<-matrix(c("a","b","c","d"),2,2)
class(m2)
typeof(m2)
a<-m2[[1]]
c<-m2[[3]]
bd<-m2[2,]
a
c
bd
```
```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList 
```

```{r}
StuDF <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuDF 
```

```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```
```{r}
class(StuDF)
typeof(StuDF)
```

```{r}
class(StuList)
as.data.frame(StuList) -> StuDF3

class(StuDF3)
StuDF3
as.data.frame(StuList,stringsAsFactors = F) -> StuDF4
class(StuDF4)
StuDF4
```
```{r}
logiCorrect<-str_length(birthday)==8
logiCorrect
```

```{r}
StuList <- list(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50)
  )
StuList 
StuList[[2]][3]
```
```{r}
class(StuDF)
typeof(StuDF)
```
```{r}
LETTERS # R內設元素值為英文字母群的character vector
chosenLETTERS <- LETTERS[1:15]
matObj1 <- matrix(chosenLETTERS,5,3)
matObj1
```
```{r}
chosenLETTERS[8]
matObj1[8]
```
```{r}
matObj1
matObj1[3,2] 
matObj1[c(F,F,TRUE,F,F),c(F,TRUE,F)]
```

```{r}
matObj1[c(1,5),c(2,3)]
```
```{r}
StuDF
StuDF[c("姓名","成績")] 
StuDF[1:5,c("姓名","成績")] 
```

```{r}
library(readr)
classSurvey <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/classSurvey.csv")
```
```{r}
StuDF2 <- data.frame(
  學號=c(172,214,322,425,517),
  姓名=c("小明","大雄","胖虎","小新","大白"),
  成績=c(80,60,90,70,50),
  stringsAsFactors = FALSE
  )
StuDF2 
```
```{r}
colnames(StuDF2)[c(2,3)] <- c("name","grades")
StuDF2
```
```{r}
colnames(StuDF2)
```

```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)
b[[3]]<-"FALSE"
b[[5]]<-7
b
```
```{r}
b <- list(
元素1=1,
元素2="Hello",
元素3=TRUE
)

b[c(3,5)] <- c('False','7')
b

b <- list(
元素1=1,
元素2="Hello",
元素3=TRUE
)

b[c(3,5)] <- c('False','7')
b
```
```{r}
b <- list(
  元素1=1,
  元素2="Hello",
  元素3=TRUE
)
b
b[[3]] <- "False"
b[[5]] <- "7"
b
b$元素2 <- "Hi"
b$`新成員` <- c(2L,5L,1L)
b
_

```
```{r}
library(readr)
exData3 <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/exData3.csv",
                    col_types = cols(
                      匯率 = col_number(),
                      期間 = col_character()))
```
```{r}
library(lubridate)
exData3$期間 <- ymd(exData3$期間)
class(exData3$期間)
```
```{r}
isAsiaCrisis <- ( date >="1997-06-01" & date<="1998-12-01")
isAsiaCrisis
```
```{r}
log<-transcriptDataFinal$學號=="92aS67fee"
transcriptDataFinal[log,]
```
```{r}
num <- function(x,.alpha){
  num1 <- x+.alpha # 程序產生output值
  return(num1) # 傳回output值
}
num(2,4)
```
```{r}
Supply <- function(a,b,p){
  o <- a+b*p
  return(o)
}

Supply(1,2,3)
```
```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent

  subSample <- transcriptDataFinal[logiChosenStudent,]

  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  return(GPA)
}

```
```{r}
invoiceList$訂單時區 == "America/New_York" -> nyLogical
invoiceList$訂單時區 == "Asia/Taipei" -> tpLogical
invoiceList$nyLogical <- nyLogical
invoiceList$tpLogical <- tpLogical

nyDateTime<-ymd_hms(invoiceList$訂單時區之下單時間[nyLogical],tz="America/New_York")

tpDateTime<-ymd_hms(invoiceList$訂單時區之下單時間[tpLogical],tz="Asia/Taipei")

invoiceList$UTC時間[nyLogical] <- with_tz(nyDateTime,tz="UTC")

invoiceList$UTC時間[tpLogical] <- with_tz(tpDateTime,tz="UTC")

invoiceList
```
```{r}
ymd_hms_tzChange <- function(ny){
 ny <- ymd_hms("1973-02-21 12:05:22",tz="America/New_York")
tp <- with_tz(ny,tz="成Asia/Taipei")
  return(tp)
}
  
```

```{r}
a <- readline(prompt = "-1")
if(a < 0) {
  print("a為負值")
}
```

```{r}
demand_supply_fun<-function(P,a,b,c,d){
  Qs<-a+P*b
  Qd<-c+P*d
  overdemand<-Qs-Qd
  return(list(
    "供給"=Qs,
    "需求"=Qd,
    "超額供給"=overdemand
  ))
}
```

```{r}
gpa_fun <- function(studentID){
  transcriptDataFinal$學號==studentID -> logiChosenStudent

  subSample <- transcriptDataFinal[logiChosenStudent,]

  sum(subSample$學期成績*subSample$學分數)/
    sum(subSample$學分數) -> GPA
  if(studentID %in% transcriptDataFinal$學號){
  return(GPA)
  }else{
      message("查無此學號")
    }
}

gpa_fun("92aS67fee") # 顯示82.85276
gpa_fun("aa829838s") # 查無此學號
```

```{r}
utility_cobb_douglass <- function(x,y,.alpha,.beta){
  utilValue <- x^.alpha*y^.beta # 程序產生output值
  return(utilValue) # 傳回output值
}

```

```{r}
a <- readline(prompt = "請輸入一個數字： ")
if(a==1) {
  print("你輸入了1")
} else if(a==2) {
  print("你輸入了2")
} else if(a==3) {
  print("你輸入了3")
} else {
  print("你輸入了其他數字")
}
```
```{r}
fizzbuzz<-function(x){
  if(x%%3==0&x%%5!=0){
    print("fizz")
  }
  else if(x%%5==0&x%%3!=0){
    print("buzz")
  }
  else if(x%%5==0&x%%3==0){
    print("fizzbuzz")
  }
  else{
    print(x)
  }
}

```
```{r}
fizzbuzz <- function(number){
  if(number %% 15== 0){
    return("fizzbuzz")}
    else if(number%% 3 ==0){
      return("fizz")
    }else if (number%% 5 == 0){
      return("buzz")
    }else {
      return(number)
    }
  }
```
```{r}
a <- c(1,3,5)
a>2 # 此邏輯條件產生三個值
if(a>2) {
  print("a大於2")
}
```
```{r}
a>2
any(a>2)
```

```{r}
saveCommitAuthor <-
  vector("character",length(commitHistory)) # 0.
for(i in seq_along(commitHistory)){
  commitHistory[[i]]$commit$author$name -> saveCommitAuthor[[i]]
}

saveCommitAuthor
```

